version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ntsearch

  backend:
    build: ./school
    networks:
      - ntsearch
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_NAME: mydb
    ports:
      - "3001:3001"

  front:
    build:
      context: ./school-app # Build frontend from ./school-app directory
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ntsearch

networks:
  ntsearch:
    driver: bridge
